name: 'Run shellcheck with reviewdog'
description: '🐶 Run shellcheck with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
    required: false
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: false
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
    required: false
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `file`.
    default: 'file'
    required: false
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog.
      Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: |
      Deprecated, use `fail_level` instead.
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    deprecationMessage: Deprecated, use `fail_level` instead.
    default: 'false'
    required: false
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false
  path:
    description: "Base directory to run shellcheck. Same as `[path]` of `find` command."
    default: '.'
    required: false
  pattern:
    description: "File patterns of target files. Same as `-name [pattern]` of `find` command."
    default: '*.sh'
    required: false
  check_all_files_with_shebangs:
    description: |
      Checks all files with shebangs in the repository even if they do not match the pattern.
      Default is `false`.
    default: 'false'
    required: false
  exclude:
    description: "Exclude patterns of target files. Same as `-not -path [exclude]` of `find` command."
    default: '*/.git/*'
    required: false
  shellcheck_flags:
    description: "Flags of shellcheck command."
    default: '--external-sources'
    required: false
runs:
  using: "composite"
  steps:
    - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      with:
        reviewdog_version: v0.21.0
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        SHELLCHECK_VERSION: 0.11.0
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_PATTERN: ${{ inputs.pattern }}
        INPUT_EXCLUDE: ${{ inputs.exclude }}
        INPUT_CHECK_ALL_FILES_WITH_SHEBANGS: ${{ inputs.check_all_files_with_shebangs }}
        INPUT_SHELLCHECK_FLAGS: ${{ inputs.shellcheck_flags }}

branding:
  icon: 'zoom-in'
  color: 'purple'
